# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/ohloh_scm
name: Coverity Scan

on:
  push:
    branches: [main]

jobs:
  coverity:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install ohcount dependencies
      run: |
        sudo apt-get install -y libpcre3 libpcre3-dev libmagic-dev gperf gcc ragel swig
        sudo mv /usr/bin/curl /usr/bin/curl.original
        sudo sh -c "echo 'if [ \$2 = \"--no-progress-meter\" ]; then
        curl.original \$1 \${@:3}
        else
        curl.original \$@
        fi' > /usr/bin/curl"
        sudo chmod +x /usr/bin/curl
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: vapier/coverity-scan-action@v1
      with:
        command: '${{github.workspace}}/build'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
